### ISSUE TITLE
音声ファイルの再生時間の取得

### ISSUE THREAD

**Issue by KakeruKitahara** [jphacks/F_2213#23]
`File[]`のなかに情報があるのか分からなかった．そして，sessionStrageでリンク先のみを所持している状態で`File[]`を参照して再生時間が参照できるのか知りたい．

**Comment by kajikentaro** [comment]
Fileから直接再生時間はわからないので、リンク先をnew Audioでインスタンス化して調べるか、
前もってsessionStorageに時間を保存しておく必要がある

**Comment by KakeruKitahara** [comment]
前もってというのは直接手打ちしてということ？？？

**Comment by KakeruKitahara** [comment]
audioタグにはdurationがあるので参照して数値を調べる．
